services:
  opensaas-app:
    build:
      context: .wasp/out
      dockerfile: Dockerfile
    ports:
      - "3002:8080"
    networks:
      - shared_network
    env_file:
      - .env.server
    environment:
      - PORT=8080
    restart: always

networks:
  shared_network:
    external: true
    name: stack_stack_net
